#!/bin/sh

POOLPAGE=/usr/local/www/data/status
TEMPLATESDIR=/usr/local/www/data/scripts/templates

cd $POOLPAGE
cat /dev/null > out.template

echo "<h2>NTP Hosts</h2>
<ul>" >> out.template
for X in `cat /usr/local/www/data/rrd/list-of-systems`
do
	echo "<li><a href=$X>$X</a>" >> out.template
done
echo "</ul>" >> out.template

for X in `cat /usr/local/www/data/rrd/list-of-systems`
do
	sed -e s/POOL/$X/g $TEMPLATESDIR/template >> out.template
done

sync
cat $TEMPLATESDIR/index-head out.template $TEMPLATESDIR/index-tail > index.html

# Build the indexs for the hosts.
for X in `cat /usr/local/www/data/rrd/list-of-systems`
do
	cat /dev/null > out.template
        sed -e s/POOL/$X/g $TEMPLATESDIR/template3 >> out.template
	sync
	cat $TEMPLATESDIR/index-head out.template $TEMPLATESDIR/index-tail > $X.html
	rm -f out.template
done
