#! /bin/sh

mkdir -p ../rrd/
case "$1" in
	"")	echo "Missing system name."; exit 1
esac

RRD_BIN=/usr/bin

# 26 hours and 8 days data bins

${RRD_BIN}/rrdtool create ../rrd/$1.rrd --step 300  \
	DS:offset:GAUGE:600:U:U \
	DS:sjit:GAUGE:600:U:U \
	DS:cjit:GAUGE:600:U:U \
	DS:wander:GAUGE:600:U:U \
	DS:freq:GAUGE:600:U:U \
	DS:disp:GAUGE:600:U:U \
	DS:clients:GAUGE:600:U:U \
	DS:limited:GAUGE:600:U:U \
	DS:kod:GAUGE:600:U:U \
        RRA:LAST:0.5:1:600 \
        RRA:LAST:0.5:6:700 \
        RRA:LAST:0.5:24:775 \
        RRA:LAST:0.5:288:797 \
        RRA:AVERAGE:0.5:1:600 \
        RRA:AVERAGE:0.5:6:700 \
        RRA:AVERAGE:0.5:24:775 \
        RRA:AVERAGE:0.5:288:797 \
        RRA:MAX:0.5:1:600 \
        RRA:MAX:0.5:6:700 \
        RRA:MAX:0.5:24:775 \
        RRA:MAX:0.5:288:797 \
        RRA:MIN:0.5:1:600 \
        RRA:MIN:0.5:6:700 \
        RRA:MIN:0.5:24:775 \
        RRA:MIN:0.5:288:797

echo $1 >> ../rrd/list-of-systems
./build-site.sh
