#!/bin/bash

LOG='/var/www/time.mattrude.com/logs/pool_status.txt'

echo "" > $LOG
echo -n "Last ran: " >> $LOG
date >> $LOG
echo "" >> $LOG
echo "Kirby:" >> $LOG
ntpq -p >> $LOG
echo "" >> $LOG
echo "Twyla:" >> $LOG
ssh twyla ntpq -p >> $LOG
