#!/bin/sh

RRD_BIN=/usr/bin
RRDPAGE=/var/www/time.mattrude.com/rrd
SCRIPTS=/var/www/time.mattrude.com/scripts

cd ${RRDPAGE}
if [ ! $? ]; then exit 1; fi

for X in `cat list-of-systems`
do
	sh ${SCRIPTS}/do-rrd-update ${X}
done
