#!/bin/sh

RRD_BIN=/usr/bin
RRDPAGE=/var/www/time.mattrude.com/rrd
SCRIPTS=/var/www/time.mattrude.com/scripts
STATUS=/var/www/time.mattrude.com/status

rsync -a samantha:/var/www/time.mattrude.com/rrd/samantha-client.rrd /var/www/time.mattrude.com/rrd/samantha.mattrude.com-clients.rrd
rsync -a twyla:/var/www/time.mattrude.com/rrd/twyla-client.rrd /var/www/time.mattrude.com/rrd/twyla.mattrude.com-clients.rrd
rsync -a kirby:/var/www/time.mattrude.com/rrd/kirby-client.rrd /var/www/time.mattrude.com/rrd/kirby.mattrude.com-clients.rrd

rsync -a /var/www/time.mattrude.com/rrd/kirby.mattrude.com-clients.rrd twyla:/var/www/time.mattrude.com/rrd/kirby.mattrude.com-client.rrd
rsync -a /var/www/time.mattrude.com/rrd/twyla.mattrude.com-clients.rrd twyla:/var/www/time.mattrude.com/rrd/twyla.mattrude.com-client.rrd
rsync -a /var/www/time.mattrude.com/rrd/samantha.mattrude.com-clients.rrd twyla:/var/www/time.mattrude.com/rrd/samantha.mattrude.com-client.rrd

cd ${RRDPAGE}

if [ ! $? ]; then exit 1; fi

for X in `cat list-of-systems`
do
	sh ${SCRIPTS}/do-ntp-rrdstats ${X}
	if [ ! $? ]; then exit 1; fi

	${RRD_BIN}/rrdtool graph --imgformat=PNG ${STATUS}/${X}/daily-ntp-clients-small.png \
		--width=290 --height=100 --start=-86400 --end=-300 \
		--title='Kirby - 174.143.169.159' \
		--vertical-label='Active Clients' \
		DEF:a="/var/www/time.mattrude.com/rrd/kirby.mattrude.com-clients.rrd":clients:AVERAGE \
		AREA:a#002A97FF:"" \
		GPRINT:a:LAST:"Now\:%8.2lf %s" \
		GPRINT:a:AVERAGE:"Avg\:%8.2lf %s" \
		GPRINT:a:MAX:"Max\:%8.2lf %s\n" > /dev/null

	${RRD_BIN}/rrdtool graph --imgformat PNG ${STATUS}/${X}/daily-ntp-clients.png \
		--width=600 --height=200 --start=-86400 \
		--title="${X} - Number of Active Clients" \
		--vertical-label='Number of Clients' \
		DEF:a="/var/www/time.mattrude.com/rrd/${X}-clients.rrd":clients:AVERAGE \
		DEF:b="/var/www/time.mattrude.com/rrd/${X}-clients.rrd":abusive:AVERAGE \
		AREA:a#002A97FF:"Clients:" \
		GPRINT:a:LAST:"Current\:%8.2lf %s" \
		GPRINT:a:AVERAGE:"Average\:%8.2lf %s" \
		GPRINT:a:MAX:"Maximum\:%8.2lf %s\n" \
		AREA:b#F51D30FF:"Abusive:" \
		GPRINT:b:LAST:" Current\:%8.2lf %s" \
		GPRINT:b:AVERAGE:"Average\:%8.2lf %s" \
		GPRINT:b:MAX:"Maximum\:%8.2lf %s\n" > /dev/null

	${RRD_BIN}/rrdtool graph --imgformat PNG ${STATUS}/${X}/weekly-ntp-clients.png \
		--width=600 --height=200 --start=-691200 \
		--title="${X} - Number of Active Clients" \
		--vertical-label='Number of Clients' \
		DEF:a="/var/www/time.mattrude.com/rrd/${X}-clients.rrd":clients:AVERAGE \
		DEF:b="/var/www/time.mattrude.com/rrd/${X}-clients.rrd":abusive:AVERAGE \
		AREA:a#002A97FF:"Clients:" \
		GPRINT:a:LAST:"Current\:%8.2lf %s" \
		GPRINT:a:AVERAGE:"Average\:%8.2lf %s" \
		GPRINT:a:MAX:"Maximum\:%8.2lf %s\n" \
		AREA:b#F51D30FF:"Abusive:" \
		GPRINT:b:LAST:" Current\:%8.2lf %s" \
		GPRINT:b:AVERAGE:"Average\:%8.2lf %s" \
		GPRINT:b:MAX:"Maximum\:%8.2lf %s\n" > /dev/null

	${RRD_BIN}/rrdtool graph --imgformat PNG ${STATUS}/${X}/monthly-ntp-clients.png \
		--width=600 --height=200 --start=-2629744 \
		--title="${X} - Number of Active Clients" \
		--vertical-label='Number of Clients' \
		DEF:a="/var/www/time.mattrude.com/rrd/${X}-clients.rrd":clients:AVERAGE \
		DEF:b="/var/www/time.mattrude.com/rrd/${X}-clients.rrd":abusive:AVERAGE \
		AREA:a#002A97FF:"Clients:" \
		GPRINT:a:LAST:"Current\:%8.2lf %s" \
		GPRINT:a:AVERAGE:"Average\:%8.2lf %s" \
		GPRINT:a:MAX:"Maximum\:%8.2lf %s\n" \
		AREA:b#F51D30FF:"Abusive:" \
		GPRINT:b:LAST:" Current\:%8.2lf %s" \
		GPRINT:b:AVERAGE:"Average\:%8.2lf %s" \
		GPRINT:b:MAX:"Maximum\:%8.2lf %s\n" > /dev/null

	${RRD_BIN}/rrdtool graph --imgformat PNG ${STATUS}/${X}/yearly-ntp-clients.png \
		--width=600 --height=200 --start=-31556926 \
		--title="${X} - Number of Active Clients" \
		--vertical-label='Number of Clients' \
		DEF:a="/var/www/time.mattrude.com/rrd/${X}-clients.rrd":clients:AVERAGE \
		DEF:b="/var/www/time.mattrude.com/rrd/${X}-clients.rrd":abusive:AVERAGE \
		AREA:a#002A97FF:"Clients:" \
		GPRINT:a:LAST:"Current\:%8.2lf %s" \
		GPRINT:a:AVERAGE:"Average\:%8.2lf %s" \
		GPRINT:a:MAX:"Maximum\:%8.2lf %s\n" \
		AREA:b#F51D30FF:"Abusive:" \
		GPRINT:b:LAST:" Current\:%8.2lf %s" \
		GPRINT:b:AVERAGE:"Average\:%8.2lf %s" \
		GPRINT:b:MAX:"Maximum\:%8.2lf %s\n" > /dev/null

	for a in offset sjit cjit wander freq disp jitter
	do
		${RRD_BIN}/rrdtool graph --imgformat PNG ${STATUS}/${X}/daily-ntp-${a}.png \
			--width 600 --height 200 --start -86400 \
			--title "`TZ=UTC date`" \
			--vertical-label "${X}" \
			DEF:${a}=${RRDPAGE}/${X}.rrd:${a}:LAST \
			CDEF:n${a}=${a},1000,/ \
			AREA:n${a}#002A97FF:"${a}" \
			GPRINT:n${a}:LAST:%le > /dev/null
		
		${RRD_BIN}/rrdtool graph --imgformat PNG ${STATUS}/${X}/weekly-ntp-${a}.png \
			--width 600 --height 200 --start -691200 \
			--title "`TZ=UTC date`" \
			--vertical-label "${X}" \
			DEF:${a}=${RRDPAGE}/${X}.rrd:${a}:LAST \
			CDEF:n${a}=${a},1000,/ \
			AREA:n${a}#002A97FF:"${a}" \
			GPRINT:n${a}:LAST:%le > /dev/null
		
		${RRD_BIN}/rrdtool graph --imgformat PNG ${STATUS}/${X}/monthly-ntp-${a}.png \
			--width 600 --height 200 --start -2629744 \
			--title "`TZ=UTC date`" \
			--vertical-label "${X}" \
			DEF:${a}=${RRDPAGE}/${X}.rrd:${a}:LAST \
			CDEF:n${a}=${a},1000,/ \
			AREA:n${a}#002A97FF:"${a}" \
			GPRINT:n${a}:LAST:%le > /dev/null
		
		${RRD_BIN}/rrdtool graph --imgformat PNG ${STATUS}/${X}/yearly-ntp-${a}.png \
			--width 600 --height 200 --start -31556926 \
			--title "`TZ=UTC date`" \
			--vertical-label "${X}" \
			DEF:${a}=${RRDPAGE}/${X}.rrd:${a}:LAST \
			CDEF:n${a}=${a},1000,/ \
			AREA:n${a}#002A97FF:"${a}" \
			GPRINT:n${a}:LAST:%le > /dev/null
		
	done
done

${RRD_BIN}/rrdtool graph --imgformat=PNG ${STATUS}/all-clients.png \
	--width=290 --height=72 --start=-86400 \
	--title='Active Clients on All Servers' \
	--vertical-label='Active Clients' \
	DEF:a="/var/www/time.mattrude.com/rrd/kirby.mattrude.com-clients.rrd":clients:AVERAGE \
	DEF:b="/var/www/time.mattrude.com/rrd/twyla.mattrude.com-clients.rrd":clients:AVERAGE \
	DEF:c="/var/www/time.mattrude.com/rrd/samantha.mattrude.com-clients.rrd":clients:AVERAGE \
	LINE1:a#002A97FF:"Kirby:" \
	GPRINT:a:LAST:"Now\:%6.2lf %s" \
	GPRINT:a:AVERAGE:"Avg\:%6.2lf %s" \
	GPRINT:a:MAX:"Max\:%6.2lf %s\n" \
	LINE1:b#000000FF:"Twyla:" \
	GPRINT:b:LAST:"Now\:%6.2lf %s" \
	GPRINT:b:AVERAGE:"Avg\:%6.2lf %s" \
	GPRINT:b:MAX:"Max\:%6.2lf %s\n" \
	LINE1:c#990000FF:"Saman:" \
	GPRINT:c:LAST:"Now\:%6.2lf %s" \
	GPRINT:c:AVERAGE:"Avg\:%6.2lf %s" \
	GPRINT:c:MAX:"Max\:%6.2lf %s\n" > /dev/null

rm -f /var/www/time.mattrude.com/logs/ntp-stats-samantha.log /var/www/time.mattrude.com/logs/ntp-stats-twyla.log

ssh samantha /home/matt/bin/ntp/ntp_clients_stats > /var/www/time.mattrude.com/logs/ntp-stats-samantha.log
ssh twyla /home/matt/bin/ntp/ntp_clients_stats > /var/www/time.mattrude.com/logs/ntp-stats-twyla.log
